//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandwichShopKios.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SandwichShopKios.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_WhiteChocolate_strawberryDessert___Copy {
            get {
                object obj = ResourceManager.GetObject("Black&WhiteChocolate&strawberryDessert - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_WhiteChocolateStrawberryandGrapesDessert {
            get {
                object obj = ResourceManager.GetObject("Black&WhiteChocolateStrawberryandGrapesDessert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buxton_waterBottle_soft_drink_water_bottle_bottled_water_mineral_water_water_bottle_food_label_thumbnai {
            get {
                object obj = ResourceManager.GetObject("Buxton-waterBottle-soft-drink-water-bottle-bottled-water-mineral-water-water-bott" +
                        "le-food-label-thumbnai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buxton_waterBottle_soft_drink_water_bottle_bottled_water_mineral_water_water_bottle_food_label_thumbnai1 {
            get {
                object obj = ResourceManager.GetObject("Buxton-waterBottle-soft-drink-water-bottle-bottled-water-mineral-water-water-bott" +
                        "le-food-label-thumbnai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cheese_and_salad_sandwich {
            get {
                object obj = ResourceManager.GetObject("Cheese and salad sandwich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChickenSandwich {
            get {
                object obj = ResourceManager.GetObject("ChickenSandwich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PepsiMaxDrink {
            get {
                object obj = ResourceManager.GetObject("PepsiMaxDrink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_250_ml_red_bull_energy_drink_can_energy_drink_red_bull_soft_drink_monster_energy_ounce_red_bull_grocery_ {
            get {
                object obj = ResourceManager.GetObject("png-clipart-250-ml-red-bull-energy-drink-can-energy-drink-red-bull-soft-drink-mon" +
                        "ster-energy-ounce-red-bull-grocery-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_burger_and_sandwich_burger_and_sandwich_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-burger-and-sandwich-burger-and-sandwich-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_buxton_water_bottle_soft_drink_water_bottle_bottled_water_mineral_water_water_bottle_food_label_thumbnai {
            get {
                object obj = ResourceManager.GetObject("png-clipart-buxton-water-bottle-soft-drink-water-bottle-bottled-water-mineral-wat" +
                        "er-water-bottle-food-label-thumbnai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_buxton_water_bottle_soft_drink_water_bottle_bottled_water_mineral_water_water_bottle_food_label_thumbnai1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-buxton-water-bottle-soft-drink-water-bottle-bottled-water-mineral-wat" +
                        "er-water-bottle-food-label-thumbnai1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_chocolate_cake_birthday_cake_sponge_cake_chocolate_brownie_torte_cake_platter_food_baking_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-chocolate-cake-birthday-cake-sponge-cake-chocolate-brownie-torte-cake" +
                        "-platter-food-baking-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_chocolate_cake_ice_cream_cake_cupcake_birthday_cake_cake_cream_food_thumbnail___Copy {
            get {
                object obj = ResourceManager.GetObject("png-clipart-chocolate-cake-ice-cream-cake-cupcake-birthday-cake-cake-cream-food-t" +
                        "humbnail - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_coca_cola_zero_beverage_can_coca_cola_fizzy_drinks_rc_cola_diet_coke_coca_food_cola_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-coca-cola-zero-beverage-can-coca-cola-fizzy-drinks-rc-cola-diet-coke-" +
                        "coca-food-cola-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_cream_chocolate_brownie_fudge_mongolian_cuisine_dessert_desserts_food_recipe_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-cream-chocolate-brownie-fudge-mongolian-cuisine-dessert-desserts-food" +
                        "-recipe-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_cupcake_icing_dessert_strawberry_cake_food_frozen_dessert_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-cupcake-icing-dessert-strawberry-cake-food-frozen-dessert-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_fanta_orange_soda_can_illustration_fizzy_drinks_coca_cola_fresca_fanta_orange_soft_drink_fanta_orange_or {
            get {
                object obj = ResourceManager.GetObject("png-clipart-fanta-orange-soda-can-illustration-fizzy-drinks-coca-cola-fresca-fant" +
                        "a-orange-soft-drink-fanta-orange-or", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_fruit_salad_breakfast_dessert_salad_natural_foods_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-fruit-salad-breakfast-dessert-salad-natural-foods-food-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_greek_salad_caesar_salad_pasta_salad_recipe_salad_leaf_vegetable_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-greek-salad-caesar-salad-pasta-salad-recipe-salad-leaf-vegetable-food" +
                        "-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_greek_salad_caesar_salad_wrap_bean_salad_pasta_salad_salad_vegetable_salad_leaf_vegetable_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-greek-salad-caesar-salad-wrap-bean-salad-pasta-salad-salad-vegetable-" +
                        "salad-leaf-vegetable-food-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_ham_and_cheese_sandwich_hamburger_sandwich_french_fries_sandwich_food_recipe_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-ham-and-cheese-sandwich-hamburger-sandwich-french-fries-sandwich-food" +
                        "-recipe-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_orange_juice_orange_drink_orange_soft_drink_juice_food_photography_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-orange-juice-orange-drink-orange-soft-drink-juice-food-photography-th" +
                        "umbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_pepsi_fizzy_drinks_coca_cola_drink_can_pepsi_cola_electric_blue_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-pepsi-fizzy-drinks-coca-cola-drink-can-pepsi-cola-electric-blue-thumb" +
                        "nail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_romaine_lettuce_greek_salad_caesar_salad_fattoush_green_salad_leaf_vegetable_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-romaine-lettuce-greek-salad-caesar-salad-fattoush-green-salad-leaf-ve" +
                        "getable-food-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_submarine_sandwich_cheesesteak_chicken_sandwich_barbecue_chicken_gyro_cheese_sandwich_food_recipe_thumbn {
            get {
                object obj = ResourceManager.GetObject("png-clipart-submarine-sandwich-cheesesteak-chicken-sandwich-barbecue-chicken-gyro" +
                        "-cheese-sandwich-food-recipe-thumbn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_sundae_chocolate_ice_cream_acai_palm_petit_gateau_ice_cream_cream_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-sundae-chocolate-ice-cream-acai-palm-petit-gateau-ice-cream-cream-foo" +
                        "d-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_vegetable_salad_dish_fruit_salad_israeli_salad_pasta_vegetable_fruit_salad_natural_foods_leaf_vegetable_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-vegetable-salad-dish-fruit-salad-israeli-salad-pasta-vegetable-fruit-" +
                        "salad-natural-foods-leaf-vegetable-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_vegetable_salad_green_papaya_salad_thai_cuisine_salted_duck_egg_thai_salads_salad_food_seafood_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-vegetable-salad-green-papaya-salad-thai-cuisine-salted-duck-egg-thai-" +
                        "salads-salad-food-seafood-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SevenUpDrink {
            get {
                object obj = ResourceManager.GetObject("SevenUpDrink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Smallbuxton_water_bottle_soft_drink_water_bottle_bottled_water_mineral_water_water_bottle_food_label_thumbnai {
            get {
                object obj = ResourceManager.GetObject("Smallbuxton-water-bottle-soft-drink-water-bottle-bottled-water-mineral-water-wate" +
                        "r-bottle-food-label-thumbnai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tuna_TomatosSandwich {
            get {
                object obj = ResourceManager.GetObject("Tuna&TomatosSandwich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tuna_TomatosSandwich1 {
            get {
                object obj = ResourceManager.GetObject("Tuna&TomatosSandwich1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waterpngegg4 {
            get {
                object obj = ResourceManager.GetObject("Waterpngegg4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
